### Create user
POST http://localhost:3030/api/users
Content-Type: application/json

{
    "username": "test5",
    "password": "test5"
}

### Login user
POST http://localhost:3030/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}