### Create user
POST http://localhost:3030/api/users
Content-Type: application/json

{
    "username": "test5",
    "password": "test5"
}

### Login user
POST http://localhost:3030/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "test"
}

### Add book
POST http://localhost:3030/api/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0ZDkyOWQ2ODg3OTQ3NjNjOTQ3NDMwYiIsImlhdCI6MTY5NTU4ODY5Mn0.2jpit26-LnAi0QDCeYRvRmzIV63qt8yxDE0HF42YLlM

{
    "bookUrl": "https://react-reader.metabits.no/files/alice.epub"
}

###
GET http://localhost:3030/api/books
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0ZDkyOWQ2ODg3OTQ3NjNjOTQ3NDMwYiIsImlhdCI6MTY5NTU4ODY5Mn0.2jpit26-LnAi0QDCeYRvRmzIV63qt8yxDE0HF42YLlM

###
POST http://localhost:3030/api/translate
Content-Type: application/json

{
    "word": "Hello"
}


###
GET http://localhost:3030/api/dictionary
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0ZDkyOWQ2ODg3OTQ3NjNjOTQ3NDMwYiIsImlhdCI6MTY5NTU4ODY5Mn0.2jpit26-LnAi0QDCeYRvRmzIV63qt8yxDE0HF42YLlM

###
POST http://localhost:3030/api/dictionary
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY0ZDkyOWQ2ODg3OTQ3NjNjOTQ3NDMwYiIsImlhdCI6MTY5NTU4ODY5Mn0.2jpit26-LnAi0QDCeYRvRmzIV63qt8yxDE0HF42YLlM

{
    "text": {
        "wordEn": "Hoba",
        "wordRu": "Хоба"
    } 
}